version: '2'
services:
  gitty:
    build: .
    command:
      - gunicorn
      - server:__hug_wsgi__
      - --bind
      - 0.0.0.0:8000
      - -k
      - gevent
      - --log-level
      - DEBUG
      - --reload
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
